# Section 7.1 

## Question 1 - Using EVregistry, Write a query to select the ModelYear, Make, and Model off all of the vehicles in the registry.

```sql

SELECT ModelYear, Make, Model

FROM EVRegistry

```

## Question 2 - Using the EVRegistry table, Write a query that lists all of the unique types of EV's. your reult set should have one column, ElectricVehicleType.

```sql

SELECT DISTINCT 

    ElectricVehicleType 

FROM 

    EVRegistry;

```

## Question 3 - Using the EVRegistry, Write a query that shows all of the information on Battery Electric Vehicles (BEV) that are in the registry.

```sql

SELECT *

FROM EVRegistry

WHERE ElectricVehicleType = "Battery Electric Vehicle (BEV)";

```

## Question 4 - Using the EVRegistry, wirte a query that returns the Make and Model of all of the EV's that have a BaseMSRP between 20000 and 35000?

```sql

SELECT Make, Model

FROM EVRegistry

WHERE BaseMSRP BETWEEN 20000 and 35000;

```


#7.2 HW Questions

## Question 1 - Using EVRegistry, write a query to find a record where the City attribute is NULL. Return all of the available columns.

```sql

SELECT *

FROM EVRegistry

WHERE City IS NULL

```

## Question 2 - Write a query to find the make, model, and ElectricVehicleType where the VIN number has that ends in '3E1EA1J'.

```sql

SELECT Make, Model, ElectricVehicleType

FROM EVRegistry

WHERE VIN LIKE "%3E1EA1J";

```

## Question 3 - Select the ModelYear, make, model, ElectricVehicleType, and range of the Tesla vehicles or cheverolet vehicles in the registry. Order the result set by Make and Model year in from newest to oldest.

```sql

SELECT 

    ModelYear, 

    Make, 

    Model, 

    ElectricVehicleType, 

    ElectricRange 

FROM 

    EVRegistry

WHERE 

    Make IN ("TESLA", "CHEVROLET")

ORDER BY 

    Make ASC, 

    ModelYear DESC;

```



## Question 4 - Using EVCharging, Write a query to find out how many many times those stations were used. Order them by the most used to the least used and limit the output to 5 records.

```sql

SELECT 

    StationID, 

    COUNT(*) AS UsageCount 

FROM 

    EVCharging

GROUP BY 

    StationID

ORDER BY 

    UsageCount DESC

LIMIT 5;

```

## Question 5 - Using EVCharging, For the folks who charged longer than 0.5 hours, show the min and max of the charging time for each user. Your output columns should be userid, minTime, and maxTime. Order this result set by the last two columns respectively.

```sql

SELECT 

    userId, 

    MIN(chargeTimeHrs) AS MinTime, 

    MAX(chargeTimeHrs) AS MaxTime

FROM 

    EVCharging

WHERE 

    chargeTimeHrs > 0.5

GROUP BY 

    userId

ORDER BY 

    MinTime ASC, 

    MaxTime ASC;


```

# Section 7.3

## Question 1 - Using EVCharging, Which day of the week has the highest average charging time? Round the answer to 2 decimal points.

```sql
SELECT 

    weekday AS DayOfWeek, 

    ROUND(AVG(chargeTimeHrs), 2) AS AvgChargingTime

FROM 

    EVCharging

GROUP BY 

    weekday

ORDER BY 

    AvgChargingTime DESC

LIMIT 1;

```


## Question 2. Using, EV charging, Find the total power consumed from charging EV's by each User. Return the userId and name the calculated column, totalPower. Round the answer to 2 deciaml points and list the out put in highest to lowest order. Limit the order to the top 15 users.

```sql

SELECT 

    userId, 

    ROUND(SUM(kwhTotal), 2) AS totalPower

FROM 

    EVCharging

GROUP BY 

    userId

ORDER BY 

    totalPower DESC

LIMIT 15;

```


## Question 3. Using dimfacility and factCharge, write a query to find out which type of facility (GROUP BY) has the most amount of charging stations. Return type Facility and name the calculated column numStation. Order the result set from highest to lowest number of charging stations.

```sql

SELECT 

    typeFacility, 

    COUNT(stationID) AS NumStation

FROM 

    dimFacility AS DF

JOIN 

    factCharge AS FC

ON 

    DF.FacilityKey = FC.facilityID

GROUP BY 

    typeFacility

ORDER BY 

    NumStation DESC;

```

## Question 4. In your own words, Briefly explain Primary Keys and Foreign Keys.


Primary Key: A column (or a set of columns) in a table that uniquely identifies each record in that table. 

- It ensures data integrity by preventing duplicate entries. For example, UserID in a Users table.



Foreign Key: A column (or a set of columns) in one table that references the Primary Key in another table. 

- It establishes a relationship between the two tables. For example, FacilityID in a factCharge table referencing FacilityID in the dimFacility table.


## Question 5 - Using EV Charging, For the folks who charged longer than one hour, show the min and max of the charging time for each user. Your output columns should be userid, minTime, and maxTime. Order this result set by the last two columns respectively. HINT: USE HAVING

```sql

SELECT 

    userId, 

    MIN(chargeTimeHrs) AS MinTime, 

    MAX(chargeTimeHrs) AS MaxTime

FROM 

    EVCharging

GROUP BY 

    userId

HAVING 

    MIN(chargeTimeHrs) > 1

ORDER BY 

    MinTime ASC, 

    MaxTime ASC;

```